### ISSUE TITLE
Known issues & ToDo list

### ISSUE THREAD

**Issue by PeterBocan** [PeterBocan/QtMacExtras#1]
Known issues: 
 
 - [ ] Base sizing elements in Toolbar
 - [ ] Resizing elements in Toolbar

ToDo List:

 - [ ] Merge/Use native widgets (QPushButton, QComboBox, etc.) instead of custom ones ?
 - [ ] Native Split-view widget
 - [ ] Implement other OS X native goodies.
